# Generated by Django 4.0.3 on 2022-04-10 12:21

from django.db import migrations

from server_app_api.house_importer import import_house_items


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
