# Generated by Django 4.0.3 on 2022-04-10 12:22

from django.db import migrations, models

from server_app_api.house_importer import import_house_items


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('server_app_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AveragePriceBusinessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_sell_price', models.PositiveIntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousePersistenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_uuid', models.CharField(default='', max_length=40)),
                ('primary_addressable_object_name', models.CharField(max_length=50)),
                ('secondary_addressable_object_name', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('sell_price', models.PositiveIntegerField()),
                ('sell_date', models.DateTimeField()),
                ('address_street', models.CharField(max_length=50)),
                ('address_locality', models.CharField(max_length=50)),
                ('address_town', models.CharField(max_length=50)),
                ('address_county', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('house_type', models.CharField(
                    choices=[('F', 'flats'), ('S', 'semi-detached'), ('D', 'detached'),
                             ('T', 'terraced')], default='F', max_length=1)),
            ],
        ),
        migrations.RunPython(
            lambda apps, schema_editor: import_house_items(apps=apps, schema_editor=schema_editor, import_limit=-1,
                                                           file_url="http://prod.publicdata.landregistry.gov.uk.s3-website-eu-west-1.amazonaws.com/pp-complete.csv")),
    ]
