# Generated by Django 4.0.3 on 2022-04-12 10:34
import os

from django.db import migrations

from server_app_api.house_importer import import_house_items


class Migration(migrations.Migration):
    dependencies = [
        ('server_app_api', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: import_house_items(apps=apps, schema_editor=schema_editor,
                                                           bulk_commit_size=os.environ.get("BULK_COMMIT_SIZE", 1000),
                                                           import_limit=os.environ.get("IMPORT_LIMIT", -1),
                                                           file_url="http://prod.publicdata.landregistry.gov.uk.s3-website-eu-west-1.amazonaws.com/pp-complete.csv")),
    ]
